model:
  n_width: 26
  n_depth: 1
  learning_rate: 0.001
  epoch_max: 5
  seed: 42

data:
  table : "workspace.default.circles"
  n_samples: 3000
  noise: 0.03
  factor: 0.8
  train_split: 0.7
  random_state: 42
  batch_size: 32

logger:
  verbosity: 1
  experiment_root : "ECML"

hpo: 
  trials: 10
  warmup_trials: 5
  warmup_steps : 2



